# https://pre-commit.com/hooks.html
types: [ file, python ]

exclude: ^tests/

default_language_version:
    python: python3.9

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [ --branch, dev ]


  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [ "--profile", "black" ]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
        exclude: alembic/env.py
        args: ["--line-length=120"]
#
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: alembic/env.py
        args: [
        "--ignore=E203,W503",
        "--max-line-length=120",
        "--per-file-ignores=tests/*.py:S101",
        "--exclude=.git __pycache__ tmp alembic/env.py",
      ]
