"""Create Item and SearchResult

Revision ID: ae3e75cf7dd8
Revises: 
Create Date: 2023-07-14 19:20:33.600235

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ae3e75cf7dd8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("item",
                    sa.Column("id", sa.String(), nullable=False),
                    sa.Column("description", sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint("id"),
                    sa.UniqueConstraint("id")
                    )
    op.create_table("search_result",
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("search_id", sa.String(), nullable=False),
                    sa.Column("similarity", sa.Float(), nullable=False),
                    sa.Column("item_id", sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(["item_id"], ["item.id"], ),
                    sa.PrimaryKeyConstraint("id")
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_result")
    op.drop_table("item")
    # ### end Alembic commands ###
